### ISSUE TITLE
[Quest] Supplies to Private Thorsen - incorrect requirements

### ISSUE THREAD

**Issue by ghost** [CookieMonsterDev/titans-league#10]
**Description**:

Quest is located in Booty Bay. This quest is meant for Alliance, however, I was able to accept the quest as Horde.

**Current behaviour**:

Supplies to Private Thorsen does not bear correct requirements. Allows incorrect faction to accept the quest.

**Expected behaviour**:

Quest should have proper requirements preventing Horde from accepting quest.

**Steps to reproduce the problem**:

1. Use Horde Character
2. Travel to Booty Bay
3. Accept quest - Supplies to Private Thorsen (Bug)

**Any other useful links here**:
https://classic.wowhead.com/quest=198/supplies-to-private-thorsen

**Comment by Cillez** [comment]
Fixed
