### ISSUE TITLE
Battered Junkbox

### ISSUE THREAD

**Issue by drlovedaddy** [CookieMonsterDev/titans-league#11]
**Description**:

Battered junkboxes don't give out loot

**Current behaviour**:

When you pickpocket a battered junkbox and unlock it as a rogue it's supposed to give some sort of loot, it doesn't give anything and just disappears

**Expected behaviour**:

Battered junkboxes are supposed to give some sort of loot when they are picklocked or opened with a key and they don't give out any loot its just disappears, without giving anything at all.

**Steps to reproduce the problem**:

Figure out what is causing the glitch/bug with the battered junkboxes being opened.

**Any other useful links here**:
https://classic.wowhead.com/item=16882/battered-junkbox

**Comment by MarkusL94** [comment]
Works as intended, none of the items that are contained inside of it have a 100% drop chance.
https://classic.wowhead.com/item=16882/battered-junkbox#contains
