### ISSUE TITLE
"The Absent Minded Prospector"

### ISSUE THREAD

**Issue by mymanjack** [CookieMonsterDev/titans-league#13]
**Description**:

"The Absent Minded Prospector" Quest Bug

**Current behaviour**:

The npc required to escort will run back to the beginning before completing the quest and will stand still as if you failed the quest but without any death to the npc and with the quest still active not set as "failed"

**Expected behaviour**:

The npc should follow you all through the place and mark the quest as "completed" when he has finished before running back to the beginning.

**Steps to reproduce the problem**:

1. Take the Quest
2. Follow the npc through the quest

**Any other useful links here**:

**Comment by Cillez** [comment]
@mymanjack I'm unable to reproduce this bug. Are you talking about the quest where he is looking for 
 a fossil and then he remembers he left them with Hollee?

**Comment by mymanjack** [comment]
I have abandoned and retook the quest which now the interaction worked correctly with him walking down the stairs as to continue the scenario, i also saw 2-3 mobs fall through the map which he was at the tent. i am not sure if these mobs some how caused the error i had when i posted this but it deffinetly did cause a weird mechanic to where the prospector would instead just walk to the front at the rock with no "quest failed"

**Comment by MarkusL94** [comment]
I also saw the second wave of creature he summoned fell under the ground and he walks back slowly when he restarts from his wp after attacking a creature, should prob make him run back to his wp instead of slowly walking. @VincentVanclef everything else worked.
https://www.youtube.com/watch?v=UeNbdd8UBMA

**Comment by VincentVanclef** [comment]
Smells like same issue as the chicken quest.
