### ISSUE TITLE
Magentizing

### ISSUE THREAD

**Issue by drlovedaddy** [CookieMonsterDev/titans-league#15]
**Description**:

Magnetizing items with same stats

**Current behaviour**:

I magnetized a chest with 9 agility and 9 stamina to my chest which already had 2 agility and 2 stamina. It took away my 2 stamina and took my agility down to 1 agility on my Chest piece

**Expected behaviour**:

Magnetizing an item should ADD the stats on to the piece you're trying to magnetize, instead it takes away from the stats and bumps it down to 0 or 1.

**Steps to reproduce the problem**:

Find out what's the cause is for losing stats on a magnetized item.

**Any other useful links here**:
https://classic.wowhead.com/item=7407/infiltrator-armor

The random enchantment was of the monkey. Used on a rogue class.

**Comment by MarkusL94** [comment]
@VincentVanclef Looks like the system doesn't recognize the enchantment on the item. When I tested it, my stamina and agility both stayed at +2, and only my Armor stat increased.

**Comment by VincentVanclef** [comment]
> @VincentVanclef Looks like the system doesn't recognize the enchantment on the item. When I tested it, my stamina and agility both stayed at +2, and only my Armor stat increased.

This is the only behavior that makes sense to me, as there is nowhere in the code i do substraction. But it doesnt account for enchantments no. Should it?

**Comment by MarkusL94** [comment]
> This is the only behavior that makes sense to me, as there is nowhere in the code i do substraction. But it doesnt account for enchantments no. Should it?

I think we should maybe add it, just so there are no future reports. However we should make it so people aren't able to stack enchantments on top of each other.
Ex; enchanting equipped item and enchanting item they want to magnet.

**Comment by MarkusL94** [comment]
Thanks for the report. We will decide on if we will make it possible to magnet items with enchants or not.
