### ISSUE TITLE
Magentizing Quest

### ISSUE THREAD

**Issue by drlovedaddy** [CookieMonsterDev/titans-league#16]
**Description**:

The start quest for magnetizing cloth to mail

**Current behaviour**:

I can't magnetize a cloth robe to a mail chest as a hunter. It tells me "can't mix armor types"

**Expected behaviour**:

I should be able to magnetize a mail chest piece with another chest piece that I have available

**Steps to reproduce the problem**:

Make the reward from the previous quest give out a chest piece of your classes designated armor type.

**Any other useful links here**:
REPLACEME

**Comment by MarkusL94** [comment]
Resolved.
Thanks for the report!
