### ISSUE TITLE
Rabies debuff

### ISSUE THREAD

**Issue by drlovedaddy** [CookieMonsterDev/titans-league#18]
**Description**:

Rabies debuff isn't a debuff.

**Current behaviour**:

When a mottled worg uses rabies you're supposed to have a debuff that reduces your stats. However it's not being labeled as a debuff, instead it says it's a buff that you can't cure or right click off.

**Expected behaviour**:

Rabies isn't supposed to be labeled as a buff as it reduces stats so it should be a debuff that you can purify or cleanse off.

**Steps to reproduce the problem**:

Find out what's causing it to be labeled as a buff and not a debuff, and why it can't be purified or cleansed.

**Any other useful links here**:
https://classic.wowhead.com/spell=3150/rabies

**Comment by MarkusL94** [comment]
Resolved,
Thanks for the Report!
