### ISSUE TITLE
Stonebind totem

### ISSUE THREAD

**Issue by drlovedaddy** [CookieMonsterDev/titans-league#2]
**Description**: 

Shaman Totems- Earthbind Totem

**Current behaviour**:

 Tell us what happens.

Earthbind Totem is bugged does not slow targets

**Expected behaviour**:

 Tell us how it's supposed to work.

It's supposed to slow down the enemies

**Steps to reproduce the problem**:

Fix the glitch with Earthbind totem so it works properly.

**Any other useful links here**:
https://classic.wowhead.com/spell=2484/earthbind-totem#modified-by

**Comment by VincentVanclef** [comment]
Lawl, was caused by Eluna. Reported the bug to rochet.

https://github.com/ElunaLuaEngine/ElunaTrinityWotlk/blob/master/src/server/game/Spells/Auras/SpellAuraEffects.cpp#L5052

Anywho, fixed.
