### ISSUE TITLE
Magnetic Item with no added Stats

### ISSUE THREAD

**Issue by mymanjack** [CookieMonsterDev/titans-league#20]
**Description**:

I found a magnetic item and clicked to have it onto my gear. it explains how the item will be destroyed but the stats will combine with my current item the magnetic item is attached to.
**Current behaviour**:

Clicking accept and adding the magnetic item just added the item name to the current gear but did not add any stats.

**Expected behaviour**:

Magnetic Item Should add stats

**Steps to reproduce the problem**:
click to add to your gear. in my case it was the item "Mighty Chain Pants"

**Any other useful links here**:
https://imgur.com/a/1hoYIsg

**Comment by MarkusL94** [comment]
@mymanjack Does your item have base stats? Like have you upgraded the item yet? In order for a magnetic item to show stats. You need at least a base stat of the stats for it to show. For example; if your item has base stamina 1 and you want to magnet a item that has 10 stamina and 5 intellect. Your stats will now be 11 Stamina, intellect will not show until you've added a base stat

**Comment by mymanjack** [comment]
oh okay, they didnt have any base stats on it. was unaware of needing a base stat for the stats to add to the item.

**Comment by MarkusL94** [comment]
Will have a more detailed write up/video soon
