### ISSUE TITLE
Endurance Training Talent

### ISSUE THREAD

**Issue by drlovedaddy** [CookieMonsterDev/titans-league#21]
**Description**:

Endurance Training talent for hunters is bugged

**Current behaviour**:

Does not give the proper % boost to health for pet or player.

**Expected behaviour**:

Supposed to give a certain % health boost to pet and player

**Steps to reproduce the problem**:

Find out what glitch or error is causing the problem for hunters and their pets not to get the proper health boost

**Any other useful links here**:
https://classic.wowhead.com/spell=19583/endurance-training

**Comment by MarkusL94** [comment]
Current issue is when applying the talent it adds 2% health to hunter, however if you do .cast 19583 it applies properly. Seems like only rank 1 is bugged, other issue is that the stat doesn't apply to pet until you dismiss it and call it back. @VincentVanclef 
https://wotlk.evowow.com/?spell=19583
