### ISSUE TITLE
Ore veins Issue

### ISSUE THREAD

**Issue by mymanjack** [CookieMonsterDev/titans-league#22]
**Description**:

Ore veins seem to be missing or of missing spawn points or Find Minerals not working
**Current behaviour**:

Doing some scouting i have yet to find ore veins in neither Elwynn (which is known to have very few spawn points) nor Dun Morogh (which is knows to have tons of spawn points)
**Expected behaviour**:

Should have a few points to mine for ore.

**Steps to reproduce the problem**:

Take mining and search for copper veins.

**Any other useful links here**:
https://classic.wowhead.com/object=1731/copper-vein
^shows areas where the veins should have spawn points at

**Comment by MarkusL94** [comment]
According to this https://wotlk.evowow.com/?object=1731 there is only supposed to be 19 copper veins. Which I've added.

**Comment by mymanjack** [comment]
Thank you for the response. I just got around to checking Elwynn Forest again and making sure to do a complete sweep checking every area for veins and still appears to be none. not sure if they just arent re spawning or something
