### ISSUE TITLE
"Bad Medicine" Remedies issue

### ISSUE THREAD

**Issue by mymanjack** [CookieMonsterDev/titans-league#23]
**Description**:
Quest informs you to retieve the Venom Fern and Jungle Remedies and the quest tells you that the venom can be found around the camp while the remedies can be found on the bodies of the medicine men and jungle fighters.

**Current behaviour**:

I have so far killed around 20-25 of the jungle fighter and medicine men npcs and have yet to have 1 of the remedies drop
**Expected behaviour**:

The npcs should be dropping some of the remedies that can be looted off their corpse

**Steps to reproduce the problem**:

Take the quest "bad Medicine" and kill and loot the above npc.

**Any other useful links here**:
https://www.wowhead.com/item=2633/jungle-remedy

**Comment by MarkusL94** [comment]
Resolved.
Thanks for the report!
