### ISSUE TITLE
"Tiger Mastery" Quest Issue

### ISSUE THREAD

**Issue by mymanjack** [CookieMonsterDev/titans-league#24]
**Description**:

Quest tells you to find the npc "Sin'Dall" and loot his paw from his corpse.

**Current behaviour**:

Sin'Dall can be killed but does not give any loot or progress towards the quest.

**Expected behaviour**:

Sin'Dall should drop the paw required for quest completion

**Steps to reproduce the problem**:

Take the quest "Tiger Mastery" and kill Sin'Dall

**Any other useful links here**:
https://classic.wowhead.com/quest=188/tiger-mastery#see-also

**Comment by MarkusL94** [comment]
Resolved.
Thanks for the report!
