### ISSUE TITLE
"Panther Mastery" Quest Issue

### ISSUE THREAD

**Issue by mymanjack** [CookieMonsterDev/titans-league#25]
**Description**:

Quest tells you to find the npc "Bhag'thera" and loot his fang from his corpse.

**Current behaviour**:

Bhag'thera can be killed but does not give any loot or progress towards the quest.
**Expected behaviour**:

Bhag'thera should drop the fang required for quest completion

**Steps to reproduce the problem**:

Take the quest "Panther Mastery" and kill Bhag'thera

**Any other useful links here**:
https://classic.wowhead.com/quest=193/panther-mastery

**Comment by MarkusL94** [comment]
Resolved.
Thanks for the report!
