### ISSUE TITLE
Quest indicator bug

### ISSUE THREAD

**Issue by mymanjack** [CookieMonsterDev/titans-league#26]
**Description**:

There seems to be no quest indicator ex. "Scorpion Stinger 0/1" below the creatures name when on a quest that requires something to drop from the npc. I have done some testing and see that it is on some quest like the starter quest but did not notice it until in badlands but recall having that a lot.

**Current behavior**:

Currently some quests with a loot able objective from creatures only shows the npcs name
**Expected behavior**:

Should Display something like "$name of item 0/1" 

**Steps to reproduce the problem**:

Take the quest "Snickerfang Jowls" quest that requires a loot able objective from a npc.

**Any other useful links here**:
https://imgur.com/a/8BSTka7 
https://imgur.com/a/nqg9RGB

**Comment by mymanjack** [comment]
If the bug has to be fixed quest by quest than you could keep this post open and i will make sure to list in the comments all the quest with this bug or i can just make a separate post for each case whichever is better

**Comment by MarkusL94** [comment]
Let's make a new issue, you may combine multiple ones in one report.
Resolved.
