### ISSUE TITLE
Dismantle bug

### ISSUE THREAD

**Issue by mymanjack** [CookieMonsterDev/titans-league#27]
**Description**:

There is a bug occurring with items with names such as "of the monkey" "of the whale" etc.. that give no stat gems when dismantling only give armor shards.

**Expected behaviour**:

When dismantling it should give stat gems depending on what stats are on the item.

**Steps to reproduce the problem**:

Find an item that has "of the _____" and dismantle it

**Any other useful links here**:
Below i have provided some items i saved to test this occurrence, i tested 3 items to make sure it was a true bug and took screenshots of before it was dismantled to show stats and an after of what gems i received.

Item 1 Before: https://imgur.com/a/a1iv1W6
Item 1 After: https://imgur.com/a/juPJdVg
Item 2 Before: https://imgur.com/a/PotA1U6
Item 2 After: https://imgur.com/a/cIJfrQQ
Item 3 Before: https://imgur.com/a/9Z046oo
Item 4 After : https://imgur.com/a/yaXQdyc

**Comment by mymanjack** [comment]
Further testing has showed that it also seems to be effecting items with "of strength" & "of agility" etc.. names. and more interesting is rings with these names are not dismantled at all as it wont destroy the item or give gems

**Comment by MarkusL94** [comment]
This is related to the item being an "enchantment" since it always applies a different one.

**Comment by VincentVanclef** [comment]
Its because those arent stats but enchant effects, which i currently am not checking
