### ISSUE TITLE
"Raptor Mastery" Quest Bug

### ISSUE THREAD

**Issue by mymanjack** [CookieMonsterDev/titans-league#28]
**Description**:

Quest tells you to find Tethis and collect his talon from his corpse

**Current behavior**:

Tethis can be found and killed but does not drop any loot

**Expected behavior**:

Tethis should drop a talon for you to look for quest completion

**Steps to reproduce the problem**:

Take the quest "Raptor Mastery" and find Tethis and kill him.

**Any other useful links here**:
https://classic.wowhead.com/quest=197/raptor-mastery

**Comment by MarkusL94** [comment]
Resolved
