### ISSUE TITLE
Ore vein Spawn Point Issue

### ISSUE THREAD

**Issue by mymanjack** [CookieMonsterDev/titans-league#29]
**Description**:

Ore veins seem to be missing some spawn points in some areas.

**Current behavior**:

There seems to be some missing ore nodes in certain areas.
**Expected behavior**:

There should be ore veins in all areas that respawn after certain period of time.

**Steps to reproduce the problem**:

Go to certain locations such as Elwynn Forest and search for veins.

**Any other useful links here**:
https://wotlk.evowow.com/?object=1731

**Additional Info**:
I will be posting all locations that i find with this issue in the comments

**Comment by MarkusL94** [comment]
They should all be spawned now. Maybe you could confirm this, we will leave it open for now. @mymanjack

**Comment by mymanjack** [comment]
Copper seems to be spawned correctly now. But all other ores seem to be also bugged. tested a lot of zones from tin, silver, iron, gold, mithril, truesilver, dark iron, and thorium and all had no ores except the silver and tin zones which only had some copper deposits

**Comment by mymanjack** [comment]
Update: Tin, silver, and gold all spawn in the world now. There is a ton of silver and gold though not sure if that matters or if you want to keep it blizzlike. but there seems to be no sign of iron in the mix @CookieMonsterDev

**Comment by MarkusL94** [comment]
Thank you, I'll take a look tomorrow @mymanjack

**Comment by mymanjack** [comment]
Update: Along with iron ore, truesilver ore deposits also seem to not be spawning

**Comment by mymanjack** [comment]
Update: Along with iron ore, Truesilver ore deposits also seem to not spawn

**Comment by Scavaro** [comment]
i agree. Iron ore spawns do not seem to be active in any of the corresponding locations

**Comment by MarkusL94** [comment]
Fixed
