### ISSUE TITLE
Agility Stat

### ISSUE THREAD

**Issue by drlovedaddy** [CookieMonsterDev/titans-league#3]
**Description**:

Agility stat is not available for upgrade for rogues.

**Current behaviour**:

I try to add the agility stat to my gear and it's not even an option it's not there at all.

**Expected behaviour**:

I should be able to add agility to my gear as it's my main stat as a rogue

**Steps to reproduce the problem**:

Find the error in the DB and fix it so us rogues can have our main stat

**Any other useful links here**:
REPLACEME

**Comment by MarkusL94** [comment]
Resolved.
Thanks for the report!
