### ISSUE TITLE
Wetlands Boat Bug

### ISSUE THREAD

**Issue by mymanjack** [CookieMonsterDev/titans-league#30]
**Description**:

Boats in wetlands dont currently work

**Current behaviour**:

The boats never arrive.

**Expected behaviour**:

Boats should arrive and take you to Dustwallow Marsh, or Howling Fjord (depending on what boat you get on)

**Steps to reproduce the problem**:

Visit wetlands docks

**Any other useful links here**:

**Comment by mymanjack** [comment]
Booty Bay also seems to be affected

**Comment by MarkusL94** [comment]
Resolved.
