### ISSUE TITLE
Not automatically learning Maul and Growl

### ISSUE THREAD

**Issue by Spydoc** [CookieMonsterDev/titans-league#32]
**Description**:

Upon hitting level 10, Druids don't automatically learn Growl and Maul.

**Current behaviour**:

You don't learn Growl and Maul when you hit level 10.

**Expected behaviour**:

You should learn Growl and Maul when you hit level 10.

**Steps to reproduce the problem**:

Make a Druid and hit level 10.

**Any other useful links here**:

https://wotlkdb.com/?spell=6795
https://wotlkdb.com/?spell=6807

**Comment by MarkusL94** [comment]
Fixed, will be available on next server restart.
