### ISSUE TITLE
Primal Fury

### ISSUE THREAD

**Issue by Spydoc** [CookieMonsterDev/titans-league#36]
**Description**:

The Feral Druid talent Primal Fury occasionally doesn't give you an extra combo point when you critically hit with a combo generating ability. And yes, I have put two points into the talent.

**Current behaviour**:

The talent Primal Fury occasionally doesn't give you an extra combo point when you critically hit with a combo generating ability.

**Expected behaviour**:

When you have two points in the Primal Fury talent, it should always give you an extra combo point when you critically hit with a combo generating ability.

**Steps to reproduce the problem**:

Put two points into the talent Primal Fury, spam a combo generating ability until you notice that you haven't received an extra combo point upon landing a critical hit.

**Any other useful links here**:

**Comment by VincentVanclef** [comment]
which ability did you use to test this with?

**Comment by VincentVanclef** [comment]
As in what combo generating ability?

**Comment by 161732** [comment]
I've seen it happening with claw and rake so far.

Edit: and shred, and ravage.

**Comment by VincentVanclef** [comment]
thank you ill get it fixed asap
