### ISSUE TITLE
Blood presence-DK

### ISSUE THREAD

**Issue by drlovedaddy** [CookieMonsterDev/titans-league#4]
**Description**:

Blood presence not working properly

**Current behaviour**:

Blood presence doesn't give the health when you deal damage

**Expected behaviour**:

You're supposed to be healed by 4% of the damage you deal

**Steps to reproduce the problem**:

Find out the cause of why blood presence isn't working properly
**Any other useful links here**:
https://www.wowhead.com/spell=50689/blood-presence

**Comment by VincentVanclef** [comment]
Can't reproduce.

https://i.imgur.com/0eCggAn.png
