### ISSUE TITLE
Leveling at cap

### ISSUE THREAD

**Issue by 161732** [CookieMonsterDev/titans-league#40]
**Description**:

When leveling at cap, the game says you're getting items instead, but fails to actually give any items.

**Current behaviour**:

Game says you don't have space in bags despite having space, so it's mailing the items. It lists Omni Crystal x 0 and Chest of Titans x 0. If this is just placeholder please disregard.

**Expected behaviour**:

Items should go into bag, or get sent to mail.

**Steps to reproduce the problem**:

Level while at 50.

**Any other useful links here**:

**Comment by Cillez** [comment]
It will say that because we removed the rewards until we either remove the script or alter it a bit. Ill make sure this gets disabled soon so there wont be any confusion :)
