### ISSUE TITLE
Spell power dismantling

### ISSUE THREAD

**Issue by 161732** [CookieMonsterDev/titans-league#41]
**Description**:

Dismantling equipment that has spell power on it is giving spell essence instead of spell power shards. Has happened with a green item and crystalline cuffs from RFC.

**Current behaviour**:

When you dismantle an item with spell power on it, you get a bunch of spell essence.

**Expected behaviour**:

Dismantling an item with spell power should give spell power shards.

**Steps to reproduce the problem**:

Dismantle an item with spell power. 

**Any other useful links here**:

**Comment by VincentVanclef** [comment]
No this is because items with spell EFFECTS give spell essence but SPELL POWER gives spell power shard. So its intentional.

**Comment by 161732** [comment]
Edit: Disregard that, [Black Mageweave Gloves](https://wotlkdb.com/?item=10003) give spell essence with no other stats on the item. No pattern that I can see.

Spell effects meaning things like chance on hit effects? I did a bit more poking around, it seems like if the item also has base stats it's treating the spellpower like an effect, but if it's only equip effects (spellpower, hit, crit etc) it treats it as spellpower.

[Simple Kilt](https://wotlkdb.com/?item=10047)/[Crimson Silk Vest](https://wotlkdb.com/?item=7058) dismantles into spellpower shards, but [Azure Silk Pants](https://wotlkdb.com/?item=7046)/[Azure Silk Vest](https://wotlkdb.com/?item=4324)/[Staff of the Blessed Seer](https://wotlkdb.com/?item=2271) dismantles into spell essence.

**Comment by VincentVanclef** [comment]
Yeah if you take for example 

https://wotlkdb.com/?item=4324

Its a spell effect that gives the spell power. But it might be confusing so ill check if the spell effect gives stats, and if it does, ill give stat shards :-)
