### ISSUE TITLE
Pirate hats ahoy!

### ISSUE THREAD

**Issue by 161732** [CookieMonsterDev/titans-league#43]
**Description**:

Bloodsail mobs in STV are dropping a quest item for a Tanaris quest, whether you have the quest or not.

**Current behaviour**:

Bloodsail Warlocks and Swashbucklers drop the pirate hat quest item for Pirate Hats Ahoy! even if you don't have the quest. Possible that other Bloodsail mobs drop it as well, but those two I know for sure.

**Expected behaviour**:

They shouldn't drop the item at all. 

**Steps to reproduce the problem**:

Kill Bloodsail mobs.

**Any other useful links here**:

https://wotlkdb.com/?npc=1563
https://wotlkdb.com/?npc=1564
https://wotlkdb.com/?item=20519
https://wotlkdb.com/?quest=8365

**Comment by MarkusL94** [comment]
Fixed.

Thanks for the report!
