### ISSUE TITLE
Potential abusement with Swapping/upgrading stats/equipment

### ISSUE THREAD

**Issue by Neverlight-Jyria** [CookieMonsterDev/titans-league#45]
**Description**:

Potential abusement with Swapping/upgrading stats/equipment
I noticed currently that if u replace any stat or upgrade any stat on any item u regain all Mana/HP This could bring abusement to the table to instantly heal out of combat and go right back into combat again with full HP/Mana pool

**Current behavior**:

If u replace any armor piece or stat upgrade it completeley refills your HP/Mana bar

**Expected behavior**:

Maximum HP/Mana should increase if these stats are upgraded but should not completeley heal you

**Steps to reproduce the problem**:

Replacing armor & Stats on your gear set

**Any other useful links here**:
Error 404 Not found

**Comment by VincentVanclef** [comment]
Well, everytime you do it i have to remove all your item stats then re-apply them to make sure everything is perfectly calculated. This will always make you have 10% hp/mana which is annoying. Its already disabled in bgs and arena ill just add a combat and duel flag as well.
