### ISSUE TITLE
Not able to Disenchant a stat on gear

### ISSUE THREAD

**Issue by Neverlight-Jyria** [CookieMonsterDev/titans-league#50]
**Description**:

Trying to disenchant a stat I do not want anymroe and its not letting me disenchant completeley. Max disenchant level is 1.

**Current behaviour**:

Disenchanting fully gives the following error "Something went wrong, try again" And downgrades to level 1 only.

**Expected behaviour**:

Completeley remove the stat and free up one of the stat slots on the gear piece.

**Steps to reproduce the problem**:

Click on a unwanted stat on the armour, click disenchant & it wont disenchant lower than level 1.
Tested on multiple characters.

**Any other useful links here**:

https://gyazo.com/d6716d1172b1023ca38614697762ab2b

**Comment by VincentVanclef** [comment]
This is fixed in next core release 👍
