### ISSUE TITLE
Tailoring: Infinitley train a recipy & wrong item linked to Recipy

### ISSUE THREAD

**Issue by Neverlight-Jyria** [CookieMonsterDev/titans-league#51]
**Description**:

U can indefinetley train the level 190 Tailoring recipy "Robe of Power" at any tailoring trainer. This item also has the wrong icon/no stats. Looks like its just a picture. 

**Current behaviour**:

U able to spam "Train" and nothing happens. You do lose the money for training. & the item itself is wrong

**Expected behaviour**:

Training should add the recipy to Tailoring with the correct item & tooltip.

**Steps to reproduce the problem**:

1. Go to any trainer for Tailoring
2. Have 190+ Tailoring.
3. Spam train the "Robe of Power"
4. No profit? :(

**Any other useful links here**:

-Tooltip
https://gyazo.com/87fbf2f1a723a135f3fe588e372d365c
https://gyazo.com/79739a54f3eab8489716911b7821f444

-Original item thats suppose to be tehre
https://wotlk.evowow.com/?item=7054

**Comment by MarkusL94** [comment]
Fixed. Will be available on next server restart.
