### ISSUE TITLE
Quest NPC Bugged. "Voodoo Dues" in STV

### ISSUE THREAD

**Issue by Neverlight-Jyria** [CookieMonsterDev/titans-league#52]
**Description**:

The quest called "Voodoo Vues" Is bugged. One NPC is nowhere to be found. We went back there multiple times on both spawn locations and no luck. The NPC missing is called Chucky (See usefull links)

**Current behaviour**:

Quest works but the only part not working is to kill Chucky. Seems like he does not exist in both spawning locations. So no way to obtain Q item

**Expected behaviour**:

2 Diffrent spawns for Chucky avaliable & it should drop the item "Chucky's Huge Ring"

**Steps to reproduce the problem**:

Be on the quest "Voodoo Dues" 

**Any other useful links here**:

-NPC 
https://classic.wowhead.com/npc=2537/chucky-ten-thumbs

-Quest
https://gyazo.com/dd77c9b0499671f21747e23d70a1d854
https://wotlk.evowow.com/?quest=609

**Comment by MarkusL94** [comment]
Fixed, will be available on next server restart!
