### ISSUE TITLE
Druid Mark of the Wild Bug

### ISSUE THREAD

**Issue by Scavaro** [CookieMonsterDev/titans-league#56]
**Description**: Druid Mark of the Wild buff not displayed/ able to cast with a scroll or flask attached to the character.

**Current behaviour**: Druid character will state "a more powerful spell is already active" when no such spell is enabled

**Expected behaviour**: Druid buff will cast and be displayed along with flask and scroll buffs such as a scroll of spirit

**Steps to reproduce the problem**: Grab a scroll and an elixir/flask, Cast said scroll/flask(or elixir), attempt to cast the druid mark of the wild buff (rank 3 specifically is where the problem was)

**Any other useful links here**:
Picture of the error: https://imgur.com/a/PveoshN
Picture of the scroll buff: https://imgur.com/a/PveoshN

**Comment by VincentVanclef** [comment]
I cant seem to reproduce this, i tried with a lot of different flasks/potions. Can you tell me what flask/potion you used?

**Comment by Scavaro** [comment]
yes i used Scroll of spirit (1), no other flasks/potions. the Flask issue was fixed awhile back, the scroll issue persists

**Comment by VincentVanclef** [comment]
thanks @Scavaro !

**Comment by VincentVanclef** [comment]
What scroll do you use where the error is still present?

**Comment by Scavaro** [comment]
Scroll of Spirit

**Comment by VincentVanclef** [comment]
Ah sorry, i misread before :P Thanks
