### ISSUE TITLE
NPC "Strike" ability

### ISSUE THREAD

**Issue by 161732** [CookieMonsterDev/titans-league#57]
**Description**:

Some mobs with the "strike" ability are doing more damage than expected.

**Current behaviour**:

Ragefire Trogg, Kolkar Marauder, Southsea Pirate, Crushridge Mauler are all doing 300+ damage with strike against ~40% armor when their normal attacks are hitting for 10-30. Probably others as well, but those ones are confirmed.

**Expected behaviour**:

Strike should be doing normal damage plus a flat amount depending on the level of the mob, I assume.

**Steps to reproduce the problem**:

Get hit by strike. Die, probably.

**Any other useful links here**:

https://wotlkdb.com/?spell=11976

https://wotlkdb.com/?npc=11318
https://wotlkdb.com/?npc=3275
https://wotlkdb.com/?npc=7855
https://wotlkdb.com/?npc=2254

**Comment by Neverlight-Jyria** [comment]
This ability is doing exactly 20% HP damage. Did excessive testing and with 1 mill hp they do exactly 200K damage

**Comment by MarkusL94** [comment]
Fixed, will be available on next scheduled server restart!
