### ISSUE TITLE
No AP gem upgrades for rogues

### ISSUE THREAD

**Issue by Neverlight-Jyria** [CookieMonsterDev/titans-league#58]
**Description**:

Rogues are not able to apply AP to gear

**Current behaviour**:

Looking the list of stats u are able to put on gear. Attack Power does not showup for Rogues

**Expected behaviour**:

Able to see and put Attack Power gems on Rogue gear

**Steps to reproduce the problem**:

Browse trought the Upgrade list of the gear pieces

**Any other useful links here**:
-Error 404 nor found

**Comment by MarkusL94** [comment]
Resolved, will be available on next Server Restart.
