### ISSUE TITLE
Auto-Revive Bug

### ISSUE THREAD

**Issue by ghost** [CookieMonsterDev/titans-league#6]
**Description**:

The server auto-revive upon logout and login bugs when you die a second time after using server auto-revive (logging in and out).

**Current behaviour**:

The bug occurs on the second death after using auto-revive. It freezes the spirit in-place as if you haven't released spirit yet and will not let you run back to your body or move what-so-ever. I noticed the auto-revive also leaves an 'unrevived' corpse behind and this is what most likely leads to the bug as I also tested this bug in a graveyard and it allowed to revive when my previous corpse (from auto-revive) was already at the graveyard.

**Expected behavior**:

The 2nd death after auto-revive should function as a regular death and allow you to run back to your body.

**Steps to reproduce the problem**:

1. Die. Yep. Just die.
2. Log out and in (To activate auto-revive)
3. Die again
4. Press "Release Spirit"
5. Bug occurs (See description and current behavior)

**Any other useful links here**:
N/A

**Comment by VincentVanclef** [comment]
Caused by me calculating the active talent tree and then setting players hp/stats to 100%. Woops.
