### ISSUE TITLE
Major issue with creating Sul'thraze the Lasher

### ISSUE THREAD

**Issue by Neverlight-Jyria** [CookieMonsterDev/titans-league#62]
**Description**:

To create Sul'thraze the Lasher u need 2 1H weapon from the ZF dungeon (see links) But u cannot equip the 1H and use the cast on the weapon without magnetizing it to you actuall 1H item.
If u magnet the 1H to your mail 1H and start the cast to create Sul'thraze the Lasher ur main 1H wil completeley get deleted. U do eventually create Sul'thraze at the cost of destroying your main 1H

**Current behaviour**:

U cannot create the 2H sword normally. You gotta magnet it to the custom 1H weapon we have and start casting the spell on the sword that way. When the cast is complete it creates Sul'thraze but destroys the custom 1H we have.

**Expected behaviour**:

Normally you equip the 1H normally and cast the spell to create Sul'thraze. The cast deletes both weapons needed for the weapon but should not delete the custom 1H weapon we have

**Steps to reproduce the problem**:

REPLACEME

**Any other useful links here**:
- 2 weapons needed:
https://classic.wowhead.com/item=9380/jangthraze-the-protector
https://classic.wowhead.com/item=9379/sangthraze-the-deflector

-Spell ID
https://classic.wowhead.com/spell=11654/call-of-sulthraze

-Final Product:
https://classic.wowhead.com/item=9372/sulthraze-the-lasher

**Comment by VincentVanclef** [comment]
It doesnt delete the custom one-hand we have, it works fine or am i misunderstanding something?

https://drive.google.com/uc?id=1aOd8gdBsBJXMCSblXkj-sVT1jyV47lqU <- check this, looks to work for me.

Ill be closing this, if you disagree just post a comment here
