### ISSUE TITLE
Dungeon: Scarlet Monastery

### ISSUE THREAD

**Issue by Neverlight-Jyria** [CookieMonsterDev/titans-league#63]
**Description**:

None of these dungeons are implemented. The dungeons are empty.

**Current behaviour**:

Entering the dungeon u see no enemies or bosses. 

**Expected behaviour**:

All enemies and mobs avaliable in the dungeon upon dungeon enter/reset

**Steps to reproduce the problem**:

Enter Any wing of Scarlet Monastery

**Any other useful links here**:
https://classic.wowhead.com/scarlet-monastery

**Comment by MarkusL94** [comment]
Fixed, will be available on next server restart.
