### ISSUE TITLE
Skinning Profession not scaling with others

### ISSUE THREAD

**Issue by Scavaro** [CookieMonsterDev/titans-league#65]
**Description**: Skinning profession is not scaling 

**Current behaviour**:giving 1 skill point per mob instead of 5 like the rest of the professions 

**Expected behaviour**: Giving 5 skill points per mob with the other professions

**Steps to reproduce the problem**: kill a mob and skin it

**Any other useful links here**:
picture: https://imgur.com/a/hILvCay

**Comment by Neverlight-Jyria** [comment]
Gather professions are 1x. Crafting 6x atm

**Comment by Scavaro** [comment]
Thank you for the response
