### ISSUE TITLE
Blood Fury cancelling shapeshift

### ISSUE THREAD

**Issue by 161732** [CookieMonsterDev/titans-league#68]
**Description**:

Using Blood Fury cancels your current shapeshift form.

**Current behaviour**:

Using Blood Fury shifts you back to caster form.

**Expected behaviour**:

You should stay in your current form when using Blood Fury.

**Steps to reproduce the problem**:

Enter shapeshift form, use Blood Fury.

**Any other useful links here**:

https://wotlkdb.com/?spell=33697
https://wotlkdb.com/?spell=5487

**Comment by MarkusL94** [comment]
Will be available on next server restart

**Comment by 161732** [comment]
Still seems to be happening. Also having the same issue with Troll's Berserking.

https://wotlkdb.com/?spell=26297
