### ISSUE TITLE
Auto Loot Issue

### ISSUE THREAD

**Issue by mymanjack** [CookieMonsterDev/titans-league#69]
**Description**:

There is an issue with auto looting while dismantling

**Current behavior**:

When dismantling gear with auto loot on some items do auto loot the gems but most of the time you manually have to click the gems.

**Expected behavior**:

When auto loot is on you should auto loot the gems after dismantling

**Steps to reproduce the problem**:

1. Turn on Auto Loot
2. Dismantle a piece of gear

**Any other useful links here**:
N/A

**Comment by VincentVanclef** [comment]
This is sadly not possible, as the client doesnt tell the server if you have auto loot enabled or not, and since dismantle is custom it is not known by the client properly, so i have no way of knowing serverside to trigger an auto loot :/
