### ISSUE TITLE
[Saphira] Deserter Login Bug 

### ISSUE THREAD

**Issue by ghost** [CookieMonsterDev/titans-league#7]
**Description**:
This bug occurs on the [Saphira] realm.
Upon logging in you receive the following message:
[DESERTER WARNING] Your IP-Address has been flagged as a leaver for 1 active battlegrounds, and because of that you have been given a penalty!

**Current behavior**:
Warning message occurs on login:
"Your IP-Address has been flagged as a leaver for 1 active battlegrounds, and because of that you have been given a penalty!"
Deserter debuff follows
If you log out and back in, the bug will stack twice, after two times the bug stops occurring until the debuff goes away, then it starts again and the counter continues.

**Expected behaviour**:

Deserter status should only occur when deserting a battleground, not just logging in.

**Steps to reproduce the problem**:

1.  Login and select Saphira realm
2. Bug occurs
3. Log out and in
4. Bug occurs 2nd time
5. Relog
6. Bug stops until debuff timer goes away, then counter continues after relogging. (I got up to 6 deserters and it gave me a 60-minute debuff)

**Any other useful links here**:
N/A

**Comment by MarkusL94** [comment]
Known issue, and will be moved to the realms future bugtracker
