### ISSUE TITLE
Bag Arrangement Issue

### ISSUE THREAD

**Issue by mymanjack** [CookieMonsterDev/titans-league#70]
**Description**:

There seems to be an issue with moving items in your bags with gear in them.

**Current behavior**:

When moving an item in your bag to switch it with a new slot to organize. if there is armor, weapon, or tool in that bag slot it will tel you "Mixing item types is not allowed" and does not let your organize your bag.

**Expected behavior**:

You should be able to move items around your bag freely and if dragging an item onto another item in your bags it should switch the two items positions.

**Steps to reproduce the problem**:

1. Have a weapon, tool, or piece of gear in your bag
2. Have any type of non wearable item in your bag. 
3. Drag the non wearable item over the gear to display the error message and see the items not switch positions in your bags.

**Any other useful links here**:
N/A

**Comment by VincentVanclef** [comment]
This is because of the magnetic system, i've made it so you can drag items from your back -> equipped or equipped -> bag to activate magnetizing.. but ofc this means you cant swap items :3 

Ill discuss with the team what we gonna do here.

**Comment by VincentVanclef** [comment]
Ah nvm i misunderstood the issue, and ive seen what you mean, its fixed now.
