### ISSUE TITLE
Cant Sell items to Vendors

### ISSUE THREAD

**Issue by mymanjack** [CookieMonsterDev/titans-league#71]
**Description**:

All items used for dismantling cant be sold to vendors

**Expected behavior**:

Should be able to sell items to vendors for money.

**Steps to reproduce the problem**:

Tried to sell any gear to a vendor

**Any Additional Information**:
 Its extremely difficult to gain the gold required for some features such as buying sockets, houses etc.. without the ability to sell gear for gold. Especially the gear that sells for around 4g and for the greys and whites.

**Comment by VincentVanclef** [comment]
This is up to you guys @Cillez @CookieMonsterDev you just need to give them the ItemFlagsCustom

    ITEM_FLAG2_CU_CAN_BE_SOLD           = 0x0040,   // Custom - Item can be sold

**Comment by Scavaro** [comment]
i like that idea too easier way to get gold for mounts/etc. killing dungeon mobs give alot of grey items that we dont need shards from :)

**Comment by Cillez** [comment]
Should be able to vendor items after next restart :)
