### ISSUE TITLE
Dk Starting Gear

### ISSUE THREAD

**Issue by mymanjack** [CookieMonsterDev/titans-league#76]
**Description**:

Dks are missing some necessary items for their starting gear

**Current behaviour**:

Dks are missing 2 one handed weapons which is needed for frost spec dks.

**Expected behaviour**:

Dks should have a two-handed and 2 One-Handed weapons in their inventory as to be able to play all 3 talent specs accurately 
**Steps to reproduce the problem**:

Create a DeathKnight

**Any other useful links here**:
N/A

**Comment by MarkusL94** [comment]
Added to starting gear for all NEW DK's
