### ISSUE TITLE
Limited Item Bug

### ISSUE THREAD

**Issue by Scavaro** [CookieMonsterDev/titans-league#78]
**Description**: Limited Items (such as gear and weapons) sold by vendors can be bought out infinitely instead of just the one or two items and waiting a few hours. 

**Current behaviour**:When you purchase a piece of gear with a (1) in the upper corner showing the vendor has a cool down after you purchase that one item, and come back at that exact time of cool down you can buy as many as you want

**Expected behaviour**: Purchase the limited item from the vendor, wait 1-5 hours (however long the cooldown is) and purchase one item only before the cooldown happens again

**Steps to reproduce the problem**: find a weapon or gear vendor that sells a limited item such as the cape vendor in duskwood (forge room) buy a cloak, wait the 2 hours, come back and try to buy as many cloaks as you want

**Any other useful links here**:

**Comment by Scavaro** [comment]
This allows players to get (basically) infinite stam,strength armor etc. shards without doing any dungeons or content

**Comment by Scavaro** [comment]
picture link: https://imgur.com/a/HvnVtPF

**Comment by VincentVanclef** [comment]
wooooooooooooops haha

https://i.imgur.com/TEmJVQa.png

i accidentally used the item entry as both parameters XD woopsie! fixed
