### ISSUE TITLE
Dk Magnetics Broke

### ISSUE THREAD

**Issue by mymanjack** [CookieMonsterDev/titans-league#79]
**Description**:

Dks should be able to apply plate gear as magnetics to their gear 

**Current behaviour**:

Applying any gear as a magnetic Plate/Mail/Leather/Cloth all say type is not valid for magnetic so they arent able to apply any gear to them for magnetics

**Steps to reproduce the problem**:

Try to apply plate shoulders to the dk gear

**Any other useful links here**:
N/A

**Comment by MarkusL94** [comment]
@mymanjack have you tried to upgrade the item first?

**Comment by mymanjack** [comment]
scavaro helped me out. turns out the quests are required first
