### ISSUE TITLE
[Saphira] De-Aggro (Dismissal) Range bug

### ISSUE THREAD

**Issue by ghost** [CookieMonsterDev/titans-league#8]
**Description**:

I'm unsure if this bug is exclusive to the blood elf starting area and will do further testing to confirm this is a whole realm issue. However, Mana Wyrms appear to not dismiss you when running away. It almost seems you can run a quarter of a region before they finally dismiss you.

**Current behaviour**:
Mana Wyrm's do not dismiss or de-aggro at the range of which they are supposed to, allowing them to chase you nearly one-quarter of a region. Virtual anchor does not activate and mob is unwilling to return to its spawn area. If mob de-aggros, it is possible to re-aggro mob before it has made its proper return

**Expected behaviour**:

A virtual anchor should be present on every mob, limiting their distance of how far they will chase you. Also, mobs should not be able to be re-aggro'd once beginning the return to their anchor.

**Steps to reproduce the problem**:

1. Walk near a Mana Wyrm
2. Attempt to flee from said Mana Wyrm
3. Bug occurs (De-aggro Range)

**Any other useful links here**:
I could not locate an article indicating proper dismissal range. If I do find one, then I'll update this.

**Comment by MarkusL94** [comment]
Known issue, and will be moved to the realms future bugtracker.
