### ISSUE TITLE
Sash of Silent Blades Item

### ISSUE THREAD

**Issue by mymanjack** [CookieMonsterDev/titans-league#83]
**Description**:

Sash of Silent Blade stats are as follows: +28 Agil, increases hit rating by 11, increases attack power by 30

**Current behaviour**:

Using this item as a magnetic does not give the +11 hit rating onto your gear.

**Expected behaviour**:

It should give all stats when magnetic

**Steps to reproduce the problem**:

Apply this item as a magnetic to your belt

**Any other useful links here**:
N/A

**Additional Info**:
There are several other items i have seen with this same issue. it may be due to multiple secondary stats such as the hit and attack power

**Comment by VincentVanclef** [comment]
You need the stats itself for it to trigger. E.g. this item https://wotlkdb.com/?item=31131 gives:


127 Armor
28 Agility
11 hit rating &
30 attack power

for every of those stats your item must have the same stat. E.g. you must have upgraded agility atleast once for it to benefit from the magnetic items stats.

This is a limitation i cannot go around, as there is a max of 10 stats PER item, client will not accept more. So the player has to choose which stats he wishes to benefit from. 

If you are aware of this and the issue still persists, lemme know.
