### ISSUE TITLE
Stranglethorn Vale creatures level all 80

### ISSUE THREAD

**Issue by ghost** [CookieMonsterDev/titans-league#9]
**Description**:

Every creature in STV is level 80. Making questing impossible for the appropriate level.

**Current behaviour**:

All creatures in STV are level 80.

**Expected behaviour**:

STV is a lvl 30-50 zone, all creatures have incorrect stats/lvl.

**Steps to reproduce the problem**:

N/A

**Any other useful links here**:
https://classic.wowhead.com/stranglethorn-vale

**Comment by Cillez** [comment]
Fixed
