### ISSUE TITLE
Broken icon's

### ISSUE THREAD

**Issue by Cantcel** [CookieMonsterDev/titans-league#91]
**Description**:

Quest(items acquired ): [Upgrading your items Part II]
Icons appear as "?" icon even with the patch.
-Titans Orb
-Titan Reforger

**Current behavior**:
Icons in the bag are not appearing as they should.

**Steps to reproduce the problem**:

Create a new character and start the titans league tutorial. Once you get to the quest [Upgrading your items Part II] after looting the items you will receive "Titans Orb" & "Titan Reforger".

**Comment by MarkusL94** [comment]
Thank you for the report, the issue has been resolved and will be available on next scheduled server restart.
