### ISSUE TITLE
Broken Quest Log Title

### ISSUE THREAD

**Issue by Cantcel** [CookieMonsterDev/titans-league#92]
**Description**:
Quest NPC: Gaia
Quest: [Skip Gearing Intro]
Issue: Quest title in quest log states "Missing header! (quest designers)"

**Expected behavior**:

State the proper name for this quest

**Steps to reproduce the problem**:

Obtain the quest when you start a new character

**Comment by MarkusL94** [comment]
Thank you for the report. The issue has been resolved.
