### ISSUE TITLE
Suggestion: Relocation of NPC

### ISSUE THREAD

**Issue by Cantcel** [CookieMonsterDev/titans-league#93]
**Description**:

NPC: Leeana Shadowmoon
Location: Blood Elf Starting Zone

**Current behavior**:

Her "!" exclamation mark is hidden by the rampway when following the tutorial questline.

**Expected behavior**:

Make the NPC more visible

**Steps to reproduce the problem**:

Follow the Tutorial Quest line at the start.

**Comment by MarkusL94** [comment]
I've re-located the creature.

Thanks for the suggestion!
